spring:
  config:
    import:
      - classpath:redis.yml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: todo-manager
    password: rla13628747^^todo
    url: jdbc:mysql://localhost:3306/todo?useUnicode=true&characterEncoding=utf8

